name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      
      - name: Run pre-checks
        run: |
          printenv | sort

      - uses: actions/checkout@v2

      - name: Run post-checks
        run: |
          printenv | sort

      - name: Apt list
        run: |
          sudo apt list --installed 2>/dev/null

      - uses: rokibhasansagar/slimhub_actions@main

      - name: Run last-checks
        run: |
          printenv | sort
